### ISSUE TITLE
i had to edit cmakelists in order to compile it on linux

### ISSUE THREAD

**Issue by CaesarSilva** [nedik/soldank-plus-plus#1]
I had to include this to cmakelists in order to compile it: 
`find_package(Protobuf REQUIRED)`.

I don't know if including the code above to the cmakelists would cause problems in other systems, but for me, it was the solution.

If i don't do that i get the following errors:

```
CMake Error at source/client/CMakeLists.txt:5 (add_library):
  Target "client_lib" links to target "protobuf::libprotobuf" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at source/client/CMakeLists.txt:39 (add_executable):
  Target "client" links to target "protobuf::libprotobuf" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at source/server/CMakeLists.txt:6 (add_library):
  Target "server_lib" links to target "protobuf::libprotobuf" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at source/server/CMakeLists.txt:27 (add_executable):
  Target "server" links to target "protobuf::libprotobuf" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Also, I could only compile it on linux (xubuntu 22.04.4) using g++ 13 and gcc 13. I don't know if it was a problem with my system, but by default, g++ links go g++ 11, and I thought cmake would use the newest version, that includes the new header files, from libstdc, but it didn't, i had to manually link it to g++ 12 but it didn't work and I linked g++ to g++ 12 and gcc to gcc 12 inside /usr/bin.

I could try reproducing the errors if that's useful, but after solving the protobuf issue and using the right g++ and gcc versions, I've managed to compile it.

**Comment by nedik** [comment]
Thanks for feedback! The project uses some new features from the C++23 standard which are implemented in g++13 and higher. That's why it won't compile with older version.

As for the issue, `protobuf` is only used by `GameNetworkingSockets` library and should be downloaded by vcpkg.

I'm not sure why it won't build without `find_package(Protobuf REQUIRED)` on your system because it works for me just fine on ubuntu 23.04 but I also don't see any reason not to add it if it helps, the library is needed anyways for `GameNetworkingSockets` so we might just as well check it's existence in Soldank++'s `CMakeLists.txt` too.

Would you like to add this line as your first commit? I'm also happy to add it if you don't feel like it.
